spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#logging:
#  level:
#    dev.aquashdw.community.auth.CommunityUserDetailsService: trace
#    dev.aquashdw.community.auth.CustomSuccessHandler: trace
