server:
  port: 9080

spring:
  security:
    oauth2:
      client:
        registration:
          likelion-oidc:
            provider: likelion
            client-id: likelion-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: likelion-oidc
          likelion-auth-code:
            provider: likelion
            client-id: likelion-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9080/authorized"
            scope: read
            client-name: likelion-auth-code
        provider:
          likelion:
            issuer-uri: http://localhost:10000

#spring:
#  servlet:
#    multipart:
#      file-size-threshold: 10MB
#      max-request-size: 20MB
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        #      show_sql: true
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
